Repository 2024-Winter-Bootcamp-Team-G/git-practice, pull requests merged in 2024-12, with the labels that each got.

#8 [feat]add name
  README.md
Labels: practice

#9 Add signup feat
  signup.txt
Labels: bug

#10 인사
  README.md
Labels: good first issue
